services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: dev
volumes:
  db-store:
