services:
  db:
#    image: postgres:15-alpine
#    ports:
#      - '5432:5432'
#    volumes:
#      - db-store:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: pguser
#      POSTGRES_PASSWORD: passw0rd
#      POSTGRES_DB: dev
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: dev

  dbtest:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: devtest
#volumes:
#  db-store:
