services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  # dbtest:
  #   image: mysql:8.0
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: passw0rd
  #     MYSQL_DATABASE: devtest
